name: build and deploy code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: 7501Fitness!
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09034582923492634ABCD239824ABCE9138492847ADBCE29898749237948394857395873
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60


    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run:  python3 -m pip install --upgrade pip
      - name: install all dependencies
        run:  pip install -r requirements.txt
      - name: test with pytest
        run:  |
          pip install pytest
          pytest

     


